# Generated by Django 4.1 on 2023-04-24 12:57

from django.db import migrations, models
import django.db.models.deletion
import forms.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
            options={
                'ordering': ('field__sequence',),
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_formdata', models.BooleanField(default=False)),
                ('email_workflow', models.BooleanField(default=False)),
                ('email_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(max_length=300)),
                ('placeholder', models.CharField(blank=True, max_length=300)),
                ('tooltip', models.CharField(blank=True, max_length=300)),
                ('mandatory', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(default=1)),
                ('display_in_main_view', models.BooleanField(default=True)),
                ('master_data_code', models.CharField(default='', max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('check_unique', models.BooleanField(default=False)),
                ('unique_type', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=20)),
                ('auto_sum', models.BooleanField(default=False)),
                ('deafult_value', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('style', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('api', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('values', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('ocr_view', models.BooleanField(default=False)),
                ('table_data', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('lock_status', models.CharField(default='N', max_length=300)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='FormDataComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ShareForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=300)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('permission', models.CharField(choices=[('ANYONE_WITH_LINK', 'Anyone with link'), ('RESTRICTED', 'Restricted')], default='RESTRICTED', max_length=20)),
                ('scope', models.CharField(choices=[('ADD', 'Add'), ('VIEW', 'View')], default='VIEW', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('image_header', models.FileField(default='', null=True, upload_to=forms.models.file_dir_path)),
                ('image_footer', models.FileField(default='', null=True, upload_to=forms.models.file_dir_path)),
                ('email_formdatas', models.BooleanField(default=False)),
                ('email_workflows', models.BooleanField(default=False)),
                ('email_comments', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50, null=True)),
                ('expression', models.TextField(default='', null=True)),
                ('error_message', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFieldStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('fileds', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_style', to='forms.fields')),
                ('template', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_style', to='forms.template')),
            ],
        ),
    ]
