# Generated by Django 4.1 on 2023-04-24 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareform',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_template', to='forms.template'),
        ),
        migrations.AddField(
            model_name='shareform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdatacomment',
            name='formdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formdata_data', to='forms.formdata'),
        ),
        migrations.AddField(
            model_name='formdatacomment',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data_comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdata',
            name='data',
            field=models.ManyToManyField(to='forms.data', verbose_name='data'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_form', to='forms.template'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fields',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='forms.template'),
        ),
        migrations.AddField(
            model_name='fields',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fields',
            name='validation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_validation', to='forms.validation'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_email_notification', to='forms.template'),
        ),
        migrations.AddField(
            model_name='data',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='forms.fields'),
        ),
    ]
