# Generated by Django 4.2 on 2023-05-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_template_custom_template_type_template_timmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='card_no',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
