# Generated by Django 4.1 on 2023-04-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('sign_up', models.CharField(choices=[('0', '0'), ('1', '1')], default='1', max_length=20)),
                ('title_name', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deafult_value', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('notification', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('view_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_lead', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissionsFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deafult_value', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissionsFormdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('OWNER', 'Owner'), ('MAINTAINER', 'Maintainer'), ('REPORTER', 'Reporter'), ('INDIVIDUAL', 'Individual')], default='OWNER', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('add', models.CharField(blank=True, default='', max_length=255)),
                ('edit', models.CharField(blank=True, default='', max_length=255)),
                ('remove', models.CharField(blank=True, default='', max_length=255)),
                ('view', models.CharField(blank=True, default='', max_length=255)),
                ('last_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissionsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('OWNER', 'Owner'), ('MAINTAINER', 'Maintainer'), ('REPORTER', 'Reporter'), ('INDIVIDUAL', 'Individual')], default='OWNER', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('add', models.CharField(blank=True, default='', max_length=255)),
                ('edit', models.CharField(blank=True, default='', max_length=255)),
                ('remove', models.CharField(blank=True, default='', max_length=255)),
                ('view', models.CharField(blank=True, default='', max_length=255)),
                ('last_date', models.DateField(null=True)),
            ],
        ),
    ]
