# Generated by Django 4.1 on 2023-04-24 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0002_initial'),
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissionstemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_user_template', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermissionsformdata',
            name='deafult_value',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='commons.defaultvalue'),
        ),
        migrations.AddField(
            model_name='userpermissionsformdata',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_permissions', to='forms.template'),
        ),
        migrations.AddField(
            model_name='userpermissionsformdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermissionsfields',
            name='field',
            field=models.ForeignKey(blank=True, default=12, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions_user', to='forms.fields'),
        ),
        migrations.AddField(
            model_name='userpermissionsfields',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_permissions_fields', to='forms.template'),
        ),
        migrations.AddField(
            model_name='userpermissionsfields',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_user_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teampermission',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_permissions_team', to='commons.team'),
        ),
        migrations.AddField(
            model_name='teampermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_user_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_permission_template', to='forms.template'),
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaultvalue',
            name='field',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='forms.fields'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermissionstemplate',
            unique_together={('user', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='userpermissionsformdata',
            unique_together={('user', 'template')},
        ),
        migrations.AlterUniqueTogether(
            name='teampermission',
            unique_together={('user', 'team')},
        ),
    ]
