# Generated by Django 4.1 on 2023-04-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_name', models.CharField(max_length=254)),
                ('contact_no', models.CharField(max_length=254)),
                ('contact_person', models.CharField(default='', max_length=254)),
                ('designation', models.CharField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('active', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='YES', max_length=20)),
                ('form_count', models.IntegerField(default=0)),
                ('team_count', models.IntegerField(default=0)),
                ('workflow_count', models.IntegerField(default=0)),
                ('email_count', models.IntegerField(default=0)),
                ('custome_form_count', models.CharField(choices=[('Y', 'y'), ('N', 'n')], default='N', max_length=20)),
                ('e_signature_count', models.CharField(choices=[('Y', 'y'), ('N', 'n')], default='N', max_length=20)),
                ('space_assign', models.CharField(default='', max_length=254)),
                ('monthly_submission', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BillingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billig_data', to='subscription.billing')),
            ],
        ),
    ]
