# Generated by Django 4.1 on 2023-04-24 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('completion', models.CharField(blank=True, default='', max_length=100)),
                ('is_initial', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('properties', models.CharField(blank=True, default='', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('destination_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transition_state', to='workflow.state')),
                ('origin_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_transition_state', to='workflow.state')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStateMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instance_state', to='workflow.state')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_assigned_template', to='forms.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_log_form_data', to='forms.formdata')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_log_transition', to='workflow.transition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_log_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_state', to='workflow.state')),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_form_data', to='forms.formdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('billing', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_workflow', to='subscription.billing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_data_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='transition',
            name='workflow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transition_workflow', to='workflow.workflow'),
        ),
        migrations.CreateModel(
            name='TemplateWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_template', to='forms.template')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workflow', to='workflow.workflow')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_workflow', to='workflow.workflow'),
        ),
    ]
